project:
  type: website
  output-dir: _site
  resources:
    - files/
    - events/*/images/
    - news/*/images/

website:
  title: "Innovation Information Initiative"
  site-url: "https://www.i3open.org"
  description: "Innovation Information Initiative (I³): A data collaborative for innovation datasets, analytics, and metrics. Open innovation data including patent datasets, citation graphs, and related analytics tools."

  navbar:
    background: "#016fe2"
    foreground: "#FFFFFF"
    left:
      - text: Events
        href: events.qmd
      - text: Fellows 
        href: fellows.qmd
      - text: Datasets
        href: datasets.qmd
      - text: BigQuery
        href: bigquery.qmd
      - text: About
        href: about.qmd

  page-navigation: true
  page-footer:
    left: "Innovation Information Initiative (I³) &copy; <script>document.write(new Date().getFullYear())</script>"

  search:
    location: navbar
    type: textbox
  reader-mode: true
  open-graph: true
  twitter-card: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true 



